version: 2.1
orbs:
  node: circleci/node@4.0.0
  slack: circleci/slack@3.4.2
jobs:
  build-and-test-job:
    docker:
    - image: cimg/base:stable
    executor:
      name: node/default
      tag: "14"
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - restore_cache:
          name: Restore Yarn Cache
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - save_cache:
          name: Save Yarn Cache
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      # - slack/notify:
      #     webhook: '${SLACK_WEBHOOK}'
workflows:
    build-and-test-work:
      jobs:
        - build-and-test-job
